name: Docker Image for Streamlit App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses : actions/checkout@v4
    - name : Publish the Docker Image
      run: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker push my-image-name:$(date +%s)
    - name: List local Docker images after push
      run: docker images
  
    
