name: Doker Image for Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Build l'image Docker
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Sauvegarder le modèle
        run: cp model.pkl .github/model-backup.pkl

      # Ajoutez d'autres étapes ici, si nécessaire
