name: Doker Image for Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Build l'image Docker
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag my-image-name:$(date +%s) ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$(date +%s)

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$(date +%s)

      # Ajoutez d'autres étapes ici, si nécessaire
